from enemy_data import ENEMY_SPAWN_DATA

ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = len(ENEMY_SPAWN_DATA)

#enemy constants
SPAWN_COOLDOWN = 400

#Turret constants
TURRET_LEVELS = 4
ANIMATION_STEPS = 8
ANIMATION_DELAY = 150
LEVEL_COMPLETE_REWARD = 100
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 50
DAMAGE = 5